[package]
name = "dbasync"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
phper = "0.13.1"
tokio = { version = "1", features = ["full"] }
async-std = { version = "1", features = ["attributes", "tokio1"] }
mysql_async = "0.30"
lazy_static = "1.4.0"